#!/bin/bash

cd vaderswrapper-config-app

if [[ ! -d "venv" ]]
then
    echo "Installing venv"
    python3 -m venv venv
    source venv/bin/activate
    python3 -m pip install -r requirements.txt
else
    echo "Entering venv"
    source venv/bin/activate
fi

echo "Starting Vader's Wrapper Configuration"
python3 vaderswrapper-config-app.py $*